### ISSUE TITLE
No display of Hotels and Bookings after login

### ISSUE THREAD

**Issue by abhijeetramteke** [satishjhanwer/hotel-booking-mean-stack#4]
Hello sir, the application has an issue that it does not let user log in even after sign up, it goes to next page only through fresh signing up. I have other main  issue that the list of searched hotels and current booked hotels don't come up through signing up.  The schema  'hoteldb' came with collection 'users' only. So what should I do in order to populate the data of hotel and bookings in page? Is it the issue of MongoDB server or Node.js . Please tell.

**Comment by satishjhanwer** [comment]
I have fixed all the issues, Please take the latest and check it again, I have updated README file as well, please check that on how to insert data into hotels collection.

**Comment by abhijeetramteke** [comment]
Hello sir, your corrections have resolved the issues, the new codebase is
working fine. Thank you for your help.

Regards,
Abhijeet

**Comment by satishjhanwer** [comment]
No problem at all :)
